title: Firefly Open-Source Hardware Wallet
email: hi@firefly.app
description: >- 
  Firefly is an open-source hardware wallet for Ethereum, built with open-source firmware and hardware. 
baseurl: "" 
url: "" 
twitter_username: fireflypocket
github_username:  firefly

# Build settings
theme: 
plugins:
  - jekyll-feed

include:
  - assets
  
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
