title: Firefly Open-Source Hardware Wallet
email: hi@firefly.app
description: >- # this means to ignore newlines until "baseurl:"
  Firefly is an open-source hardware wallet for Ethereum, built with open-source firmware and hardware. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fireflypocket
github_username:  firefly

# Build settings
theme: 
plugins:
  - jekyll-feed

include:
  - assets
  
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
